onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - unrs-resolver

overrides:
  '@sentry/bundler-plugins>rollup': 4.62.4
  brace-expansion@1: 1.1.18
  flatted@3.3.3: 3.4.4
  eslint-plugin-react-hooks>zod-validation-error: 4.0.2
  minimatch@3.1.2: 3.1.5
  vitest>picomatch: 4.0.5
